config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=>'',
                     :path_names=>{:sign_up=> 'inscription', :sign_in=>'connexion', :sign_out=>'deconnexion', :logout=>'profile'},
                     :controllers=>{:registrations=>'registrations'}
                     

  root 'pages#index'

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  
  resources :rooms do

            resources :reservations, only: [:create]

  end
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your_trips' => 'reservations#your_trips' 
  get '/your_reservations' => 'reservations#your_reservations' 

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations 

  
  validates :home_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 75}
  validates :summary, presence: true, length: {maximum: 600}
  validates :address, presence: true
  validates :price, numericality: {only_integer: true, greather_than: 5}
  
  geocoded_by :address
  
    
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :fullname, presence: true, length: {maximum: 50}
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  has_many :rooms
  has_many :reservations 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
       @room = Room.order("RANDOM()").limit(3) 
    end
    
    

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
     def destroy
    
          @photo = Photo.find(params[:id])
    
           room = @photo.room
    
      
          @photo.destroy
    
      
          @photos = Photo.where(room_id: room.id)
    
      
           respond_to :js
     end

    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 protected

 def update_resource(resource, params)

     resource.update_without_password(params)

 end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

    before_action :authenticate_user!
    
    def preload
           room = Room.find(params[:room_id])
           today = Date.today
           reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)
           
           render json: reservations
    end
        
    def preview
        start_date = Date.parse(params[:start_date])
        end_date = Date.parse(params[:end_date])
        
        output = {
            conflict: is_conflict(start_date, end_date)
        }
        
        render json: output
    end
    
    private
    def is_conflict(start_date, end_date)
        room = Room.find(params[:room_id])

        check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
        check.size > 0? true : false
    end

    def your_trips
    
        @trips = current_user.reservations 
    
    end
    
    def your_reservations

      @rooms = current_user.rooms

    end

    def create
        @reservation = current_user.reservations.create(reservation_params)
        redirect_to @reservation.room, notice: "Votre réservation à été enregistré"
    end

    private
    def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :price, :total)
    end

end

app/controllers/room_controller.rb
class RoomController < ApplicationController

before_action :set_room, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]
   def index
      @rooms = current_user.rooms 
   end
   
   def new
       @room = current_user.rooms.build
   end
   
   def create
       @room = current_user.rooms.build(room_params
       )
       if @room.save
           redirect_to @room, notice:"Votre annonce a été ajouté avec succès"
       else
           render :new
       end
   end
   
   def show

   end
   
   def edit

   end
   
   def update
       if @room.update(room_params
       )
       redirect_to @room, notice:"Modification enregistrée..."
       else
        render :edit
       end
   end



private
    def set_room
        @rooms = Room.find(params[:id])  
    end
    
    def room_params
       params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room,
       :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet, :is_shampoo, :is_breakfast,
       :is_heating, :is_air, :is_kitchen, :price, :active) 
    end
   
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

before_action :set_room, only: [:destroy ,:show, :edit, :update]
before_action :authenticate_user!, except: [:home ,:show]
before_action :require_same_user, only: [:destroy,:edit, :update]


    def index
        @rooms = current_user.rooms 
    end
    
    def show
        @photos = @room.photos
    end
    
    def edit
        @photos = @room.photos
    end
    
    def destroy
        @room.photos.destroy
        @room.destroy
        redirect_to rooms_path, notice:"Votre logement a été retiré"
    end
    
    def home
       @rooms = Room.all 
    end
    
    
    def update
    
           if @room.update(room_params)
    
            if params[:images]
            
                   params[:images].each do |i|
            
                        @room.photos.create(image: i)
            
                   end
            
            end
            
             redirect_to edit_room_path(@room), notice:"Modification enregistrée..."
    
           else
    
               render :edit
    
           end
    
    end
    
    def new
    
     @room = current_user.rooms.build
    
    end
    
    def create
    
        @room = current_user.rooms.build(room_params)
        
        if @room.save
        if params[:images]
        
               params[:images].each do |i|
        
                    @room.photos.create(image: i)
        
               end
        
        end
        
         @photos = @room.photos
         redirect_to edit_room_path(@room), notice:"Votre logement a été ajouté"
        
        else
        
            render :new
        
        end
    
    end
    
    private
    
    def set_room
    
         @room = Room.find(params[:id])
    
    end
    
    def room_params
    
        params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room, 
                                       :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet, 
                                       :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, 
                                       :active)
    
    end
    
    def require_same_user
        if current_user.id != @room.user_id
            flash[:danger] = "Vous n'avez pas le droit modifier cette annonce"
            redirect_to root_path
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @rooms = @user.rooms 
    end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def avatar_url(user)
        if user.avatar.present?
            user.avatar.url
        else
            'default_image.png'
        end
    end
    
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Airbnb', root_path, {:class=>"navbar-brand"} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Entrer votre recherche">
        </div>
        <button type="submit" class="btn btn-default">Rechercher</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_room_path do %>
            <i class="fa fa-home fa-lg"></i>Devenez hôte
          <% end %>
        </li>
    <% if(!user_signed_in?) %>

        <li><%= link_to 'Connexion', new_user_session_path %></li>
        <li><%= link_to 'Inscription', new_user_registration_path %></li>
    <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.fullname %>
            <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <li><%= link_to 'Mes Voyages', root_path %></li>
            <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Déconnexion',  destroy_user_session_path, method: :delete %></li>          
          </ul>
        </li>
    <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aiirbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <%= csrf_meta_tags %>
  
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render 'layouts/navigation' %>

<%= render 'shared/message' %>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>

 <div class="row"> 

        <% @photos.each do |photo| %>

             <div class="col-md-4"> 

                  <div class="panel panel-default"> 

                        <div class="panel-heading preview">

                             <%= image_tag photo.image.url() %>

                        </div>
                        <div class="panel-body">
                        
                              <span class="pull-right">
                        
                                      <%= link_to photo, remote: true, method: :delete, data: 
                                           {confirm: "Certain de vouloir supprimer cette photo?"} do %>  
                        
                                       <i class="fa fa-times fa-lg"></i>
                        
                                       <% end %>
                        
                             </span>
                        
                         </div>

                  </div>

             </div>

       <% end %>

 </div>

 <% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>     
     <div class="row">
          <div class="col-md-12 price_tag">
               <span>€<%= @room.price %></span>
               <span class="pull-right">Par nuit</span>
          </div>
     </div>
     <div class="row">
     
              <div class="col-md-6">
     
              <label>Arrivée</label>
     
              <%= f.text_field :start_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>
     
              </div>
     
              <div class="col-md-6">
     
              <label>Départ</label>
     
              <%= f.text_field :end_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control', disabled: 'true' %>
     
              </div>
     
      </div>                        

     <div id="preview" style="display: none">
          <table class="reservation-table">
               <tbody>
                    <tr>
                         <td>Nuit</td>
                         <td><span id="reservation_days"></span></td>
                    </tr>
                    <tr>
                         <td>Total</td>
                         <td><span id="reservation_sum"></span></td>
                    </tr>
               </tbody>
          </table>
     </div>

     <%= f.hidden_field :room_id, value: @room.id, placeholder: "Date " %>

     <%= f.hidden_field :price, value: @room.price, placeholder: "Prix " %>
     
     <%= f.hidden_field :total, id: 'reservation_total' %>
     </br>
     <%= f.submit "Demande de réservation ", class: "btn btn-primary wide", disabled:'true' %>

 <% end %>
 
<script>
    function unavailable(date) {
        dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
        return [$.inArray(dmy, unavailableDates) == -1];
    }
    $(function(){
        
        unavailableDates = [];
        
        $.ajax({
            url: '/preload',
            data: {'room_id': <%= @room.id %>},
            dataType: 'json',
            success: function(data) {
                $.each(data, function(arrID, arrValue){
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date);
                    d.setDate(d.getDate() +1)) {
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                })
                
                $('#reservation_start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#reservation_end_date').datepicker("option","minDate", newdate);
                        $('#reservation_end_date').attr('disabled', false);
                        
                        var start_date = $(this).datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);
                        
                        
                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                            
                        }
                            
                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);
                                        
                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }
                                
                                }
                            });
                        
                    }
                });
                
                $('#reservation_end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        $('#reservation_start_date').datepicker("option", "maxDate", selected);
                        
                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $(this).datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);
                        
                        
                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                            
                        }
                            
                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);
                                        
                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }
                                
                                }
                            });
                        
                    }
                });
                
            }
        });
        
        
    });
</script>

app/views/reservations/you_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes voyages</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.strftime('%d.%m.%y') %> au <%= trip.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes réservations</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= reservation.start_date.strftime('%d.%m.%y') %> au <%= reservation.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.user) do %>
                           <%= image_tag avatar_url(reservation.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes voyages</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.strftime('%d.%m.%y') %> au <%= trip.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/_carrousel.html.erb
<!-- Carousel -->
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
                    <% @photos.each do |photo| %>
                      <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="<%= photo.id %>" class="active"></li>
                      </ol>
                    <% end %>
            
              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
                <% end %>
              </div>
            
              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
              </a>
            </div>
        </div>
    </div>

app/views/rooms/edit.html.erb
    <%= render 'form' %>

app/views/rooms/home.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="text-center">
            <h1>Réservez des logements uniques et vivez votre destination comme un habitant.</h1>
        </div>
    </div>
</div>
<br>
<%= form_tag search_path, method: :get do %>
    <div class="row">
        <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: "Où? Destination, ville, adresse",
            class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :start_date, params[:start_date], placeholder:"Arrivée", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :end_date, params[:end_date], placeholder:"Départ", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= submit_tag "Rechercher", class:"btn btn-primary" %>
        </div>
    </div>
<% end %>
<br>
<hr>
<br>
<div class="row">
    <div class="col-md-4">
        <h4>Logements</h4>
    </div>
</div>
<div class="row">
    <% @rooms.each do |room| %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading preview">
                    <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                </div>
                <div class="panel-body">
                    <p class="home-link"><b><%= link_to room.price, room_path(room) %> € - <%= link_to room.room_type, room_path(room) %> - <%= link_to pluralize(room.bed_room, "lit"), room_path(room) %></b>
                    <br><%= link_to room.listing_name, room_path(room) %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        });
        
        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>

app/views/rooms/new.html.erb
    <%= render 'form' %>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>

 <script type="text/javascript">

     <% resource.errors.full_messages.each do |msg| %>

               toastr.error('<%= msg %>')

     <% end %>

 </script>

 <% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>

 <script type="text/javascript">

 <% @room.errors.full_messages.each do |msg| %>

 toastr.error('<%= msg %>')

 <% end %>

 </script>

 <% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>

       <script type="text/javascript">

       <% flash.each do |f| %>

        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>

         toastr['<%= type %>']('<%= f[1] %>')

       <% end %>

       </script>

 <% end %>